## import lib

In [1]:
import polars as pl

## Series & DataFrame

In [ ]:
pl.Series("ints", [1, 2, 3, 4, 5])

shape: (5,)
Series: 'ints' [i64]
[
	1
	2
	3
	4
	5
]

In [23]:
from datetime import date

df_sample = pl.DataFrame(
    {
        "name": ["Alice Archer", "Ben Brown", "Chloe Cooper", "Daniel Donovan"],
        "birthdate": [
            date(1997, 1, 10),
            date(1985, 2, 15),
            date(1983, 3, 22),
            date(1981, 4, 30),
        ],
        "weight": [57.9, 72.5, 53.6, 83.1],  # (kg)
        "height": [1.56, 1.77, 1.65, 1.75],  # (m)
    }
)

print(df_sample)

shape: (4, 4)
┌────────────────┬────────────┬────────┬────────┐
│ name           ┆ birthdate  ┆ weight ┆ height │
│ ---            ┆ ---        ┆ ---    ┆ ---    │
│ str            ┆ date       ┆ f64    ┆ f64    │
╞════════════════╪════════════╪════════╪════════╡
│ Alice Archer   ┆ 1997-01-10 ┆ 57.9   ┆ 1.56   │
│ Ben Brown      ┆ 1985-02-15 ┆ 72.5   ┆ 1.77   │
│ Chloe Cooper   ┆ 1983-03-22 ┆ 53.6   ┆ 1.65   │
│ Daniel Donovan ┆ 1981-04-30 ┆ 83.1   ┆ 1.75   │
└────────────────┴────────────┴────────┴────────┘

In [7]:
print(df_sample.head(1))

shape: (1, 4)
┌──────────────┬────────────┬────────┬────────┐
│ name         ┆ birthdate  ┆ weight ┆ height │
│ ---          ┆ ---        ┆ ---    ┆ ---    │
│ str          ┆ date       ┆ f64    ┆ f64    │
╞══════════════╪════════════╪════════╪════════╡
│ Alice Archer ┆ 1997-01-10 ┆ 57.9   ┆ 1.56   │
└──────────────┴────────────┴────────┴────────┘

In [15]:
print(df_sample.glimpse(return_as_string=True))

Rows: 4
Columns: 4
$ name       <str> 'Alice Archer', 'Ben Brown', 'Chloe Cooper', 'Daniel Donovan'
$ birthdate <date> 1997-01-10, 1985-02-15, 1983-03-22, 1981-04-30
$ weight     <f64> 57.9, 72.5, 53.6, 83.1
$ height     <f64> 1.56, 1.77, 1.65, 1.75

/tmp/ipykernel_1207155/1588847093.py:1: DeprecationWarning: the argument `return_as_string` for `DataFrame.glimpse` is deprecated. It was renamed to `return_type` in version 1.35.0.
  print(df_sample.glimpse(return_as_string=True))

In [13]:
print(df_sample.describe())

shape: (9, 5)
┌────────────┬────────────────┬─────────────────────┬───────────┬──────────┐
│ statistic  ┆ name           ┆ birthdate           ┆ weight    ┆ height   │
│ ---        ┆ ---            ┆ ---                 ┆ ---       ┆ ---      │
│ str        ┆ str            ┆ str                 ┆ f64       ┆ f64      │
╞════════════╪════════════════╪═════════════════════╪═══════════╪══════════╡
│ count      ┆ 4              ┆ 4                   ┆ 4.0       ┆ 4.0      │
│ null_count ┆ 0              ┆ 0                   ┆ 0.0       ┆ 0.0      │
│ mean       ┆ null           ┆ 1986-09-04 00:00:00 ┆ 66.775    ┆ 1.6825   │
│ std        ┆ null           ┆ null                ┆ 13.560082 ┆ 0.097082 │
│ min        ┆ Alice Archer   ┆ 1981-04-30          ┆ 53.6      ┆ 1.56     │
│ 25%        ┆ null           ┆ 1983-03-22          ┆ 57.9      ┆ 1.65     │
│ 50%        ┆ null           ┆ 1985-02-15          ┆ 72.5      ┆ 1.75     │
│ 75%        ┆ null           ┆ 1985-02-15          ┆ 72.5      ┆ 1.75     │
│ max        ┆ Daniel Donovan ┆ 1997-01-10          ┆ 83.1      ┆ 1.77     │
└────────────┴────────────────┴─────────────────────┴───────────┴──────────┘

In [12]:
print(df_sample.schema)

Schema({'name': String, 'birthdate': Date, 'weight': Float64, 'height': Float64})

## LazyFrame

Using as a query like SQL

In [16]:
lf_sample = df_sample.lazy()

print(lf_sample.collect_schema())

Schema({'name': String, 'birthdate': Date, 'weight': Float64, 'height': Float64})

In [20]:
print(lf_sample.head(1))

naive plan: (run LazyFrame.explain(optimized=True) to see the optimized plan)

SLICE[offset: 0, len: 1]
  DF ["name", "birthdate", "weight", "height"]; PROJECT */4 COLUMNS

In [19]:
print(lf_sample.head(1).collect())

shape: (1, 4)
┌──────────────┬────────────┬────────┬────────┐
│ name         ┆ birthdate  ┆ weight ┆ height │
│ ---          ┆ ---        ┆ ---    ┆ ---    │
│ str          ┆ date       ┆ f64    ┆ f64    │
╞══════════════╪════════════╪════════╪════════╡
│ Alice Archer ┆ 1997-01-10 ┆ 57.9   ┆ 1.56   │
└──────────────┴────────────┴────────┴────────┘

In [17]:
print(lf_sample.describe())

shape: (9, 5)
┌────────────┬────────────────┬─────────────────────┬───────────┬──────────┐
│ statistic  ┆ name           ┆ birthdate           ┆ weight    ┆ height   │
│ ---        ┆ ---            ┆ ---                 ┆ ---       ┆ ---      │
│ str        ┆ str            ┆ str                 ┆ f64       ┆ f64      │
╞════════════╪════════════════╪═════════════════════╪═══════════╪══════════╡
│ count      ┆ 4              ┆ 4                   ┆ 4.0       ┆ 4.0      │
│ null_count ┆ 0              ┆ 0                   ┆ 0.0       ┆ 0.0      │
│ mean       ┆ null           ┆ 1986-09-04 00:00:00 ┆ 66.775    ┆ 1.6825   │
│ std        ┆ null           ┆ null                ┆ 13.560082 ┆ 0.097082 │
│ min        ┆ Alice Archer   ┆ 1981-04-30          ┆ 53.6      ┆ 1.56     │
│ 25%        ┆ null           ┆ 1983-03-22          ┆ 57.9      ┆ 1.65     │
│ 50%        ┆ null           ┆ 1985-02-15          ┆ 72.5      ┆ 1.75     │
│ 75%        ┆ null           ┆ 1985-02-15          ┆ 72.5      ┆ 1.75     │
│ max        ┆ Daniel Donovan ┆ 1997-01-10          ┆ 83.1      ┆ 1.77     │
└────────────┴────────────────┴─────────────────────┴───────────┴──────────┘

**LazyFrame is much more efficient**

In [31]:
data = pl.read_parquet('./data/items.parquet')
data.head(2)

shape: (2, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ manufactu ┆ descripti ┆ sale_stat ┆ size     │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rer       ┆ on        ┆ us        ┆ ---      │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ i32       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000804000 ┆ 115000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ Robo Luồn ┆ 0         ┆ Không    │
│ 0046      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ thun Winw ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ intoys có ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ h…        ┆           ┆          │
│ 050202000 ┆ 99000.000 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Không    │
│ 0004      ┆ 0         ┆           ┆ phụ kiện  ┆   ┆ định      ┆ định      ┆           ┆ xác định │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [32]:
from memory_profiler import memory_usage
import time

def eager_execution(df):
    df_filter = df.filter(pl.col("brand") == "WinWinToys")
    df_agg = df_filter.group_by("category_l1").agg(pl.col("price").mean())
    return df_agg

def lazy_frame(df):
    q = (
        df.lazy()
        .filter(pl.col("brand") == "WinWinToys")
        .group_by("category_l1")
        .agg(pl.col("price").mean())
    )
    return q.collect()


def show_result(func):

    start = time.perf_counter()

    mem, result = memory_usage(
        (func,),
        retval=True,
        max_usage=True
    )

    elapsed = time.perf_counter() - start

    print(result)
    print(f"Peak Memory: {mem:.2f} MiB")
    print(f"Elapsed: {elapsed:.4f}s")
    
    
print("Eager Execution")
show_result(lambda: eager_execution(data))
print()

print("Lazy Frame")
show_result(lambda: lazy_frame(data))

Eager Execution

shape: (2, 2)
┌────────────────┬───────────────┐
│ category_l1    ┆ price         │
│ ---            ┆ ---           │
│ str            ┆ f64           │
╞════════════════╪═══════════════╡
│ Babycare       ┆ 207666.666667 │
│ Đồ chơi & Sách ┆ 248666.666667 │
└────────────────┴───────────────┘
Peak Memory: 115.52 MiB
Elapsed: 0.2746s

Lazy Frame
shape: (2, 2)
┌────────────────┬───────────────┐
│ category_l1    ┆ price         │
│ ---            ┆ ---           │
│ str            ┆ f64           │
╞════════════════╪═══════════════╡
│ Đồ chơi & Sách ┆ 248666.666667 │
│ Babycare       ┆ 207666.666667 │
└────────────────┴───────────────┘
Peak Memory: 115.96 MiB
Elapsed: 0.2067s